# Generated by Django 4.0.6 on 2022-07-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag', models.CharField(max_length=2550)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('Location', models.CharField(max_length=2550)),
            ],
        ),
        migrations.RenameModel(
            old_name='ContactFormMessages',
            new_name='ContactFormMessage',
        ),
    ]
