# Generated by Django 4.0.6 on 2022-07-06 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_order_rename_contactformmessages_contactformmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Location',
            new_name='location',
        ),
    ]
